// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var input = Fs.readFileSync("input/Week1/Year2020Day3.sample.txt", "utf8").split("\n");

console.log(Belt_Array.keepWithIndex(Belt_Array.keepWithIndex(input, (function (param, i) {
                return (i << 0) === i;
              })), (function (arr, i) {
            return arr.charAt(Caml_int32.mod_(Math.imul(i, 3), arr.length)) === "#";
          })).length);

var x = 3;

var y = 1;

exports.input = input;
exports.x = x;
exports.y = y;
/* input Not a pure module */
